### ISSUE TITLE
Temperature too high?

### ISSUE THREAD

**Issue by hsch0** [bitbank2/bme280#1]
Im running this code on a Raspberry Pi but the temperature seems a few degrees too high. In `main.c` there is this line of code:
`T -= 150; // for some reason, the sensor reports temperatures too high`
Should this be adjusted? Why is this line in the code?

**Comment by bitbank2** [comment]
I have other temperature sensors and this particular one always seems to report the temperature as higher than it actually is, so I added an adjustment. Maybe it's a manufacturing defect in the one I have.
